### ISSUE TITLE
Alterar licença para MIT

### ISSUE THREAD

**Issue by mileo** [erpbrasil/erpbrasil.base#1]
Olá pessoal,

A lib https://github.com/erpbrasil/erpbrasil.base é uma extração de https://github.com/OCA/l10n-brazil/tree/12.0/l10n_br_base/tools

Visando difundir seu uso, aumentar o número de contribuidores e aumentar a quantidade de funcionalidades. Considero primordial alterarmos sua licença para permitir o  uso em sistemas fechados. Para tanto gostaria de solicitar a autorização de vocês para alterar a licença de AGPL-3 - See http://www.gnu.org/licenses/agpl-3.0.html para MIT https://opensource.org/licenses/mit-license.php

Por favor respondam sim ou não:

- [x] @renatonlima 
- [x] @mbcosta 
- [x] @mileo 
- [x] @hendrixcosta 
- [x] @agrings 
- [x] @sadamo 
- [x] @rvalyi 
- [x] @clementmbr  
- [x] @BiancaBartolomei 

Aproveito também para convida-los a contribuir para o projeto.

Obrigado

**Comment by mileo** [comment]
Sim

**Comment by sadamo** [comment]
Sim!

**Comment by BiancaBartolomei** [comment]
Sim

**Comment by hendrixcosta** [comment]
SIM ! :+1:

**Comment by renatonlima** [comment]
Sim! 👍

**Comment by hendrixcosta** [comment]
UP!

**Comment by mileo** [comment]
@mbcosta @clementmbr @rvalyi @agrings Estamos precisando da sua atenção neste issue.

**Comment by rvalyi** [comment]
@mileo Sim por mim.

Com o porem, que eu conto com vcs para depois alterar a licenca do OCA/l10n_br_brazil/l10n_br_base na v12 por LGPL, visando exactamente o mesmo objetivo. Sendo que publico que a Akretion tentou usar dos seus copyrights para impedir Odoo SA de sair da AGPL ate o fim e ate se desgastou muito comercialmente de defender o open source. Pois sabiamos desde o inicio que essa do cliente ter seguranca juridica com as customizacoes era conversa mole apenas para criar asymetria de licenca, Odoo EE e dominar assim junto com os investidores os parceiros que ajudaram o Odoo a existir. Sao dezenas de modulos da localizacao que irao permanescer AGPL, a ideia nao eh de facilitar para algum engraçadinho fazer uma contabilidade fechada usando o nosso trabalho. Eh publico tb que a Akretion tem centenas de modulos AGPL na OCA e outras centenas AGPL fora da OCA, portanto ninguem pode suspeitar que isso seja uma agenda secreta de fechar algo.

Mas a partir do momento que perdemos a queda de braco nessa com Odoo SA e que eles mudaram o core para LGPL, nossa visão eh que a gente precisa permitir entao que customizações especificas de uma empresa possam nao ser AGPL e ainda depender do l10n_br_base que eh central e porem basico. Pois se a gente nao faz, a gente vai acabar deixando espaço para a Odoo SA arrumar algum traira da vez para fazer uma localização que sera chamada de EE friendly (nao seria a primeira vez) e que entraria pelo l10n_br_base. Nos achamos melhor ter a galera que nao quer AGPL do nosso lado na base da localização do que contra a gente. Ainda mais que se vc imaginar alguma softwarehouse, algum vertical para um franquia grande, essa galera por chegar com dinheiro...

Finalmente, @mbcosta eh funcionario da Akretion LTDA e @clementmbr tb contribuiu dentro do estagio dele. Portanto a Akretion eh dona dos copyright dessas contribuiçoes de demos autorização para essas contribuições. @agrings eh cliente nosso, vamos pedir para ele se ele poderia retornar...

A gente ve aqui a importância de decidir cedo sobre as licenças porque mudar depois eh super chato. Por isso tb que vamos propor essa mudança no l10n_br_base na v12 enquanto ainda ha tempo...

**Comment by clementmbr** [comment]
Ok pra mim também.

Em sex, 13 de set de 2019 às 18:06, Raphaël Valyi <notifications@github.com>
escreveu:

**Comment by agrings** [comment]
Sim. Desculpem a demora.
