### ISSUE TITLE
erro comando python na instalação do erpbrasil.base

### ISSUE THREAD

**Issue by thiagoblisboa** [erpbrasil/erpbrasil.base#23]
Olá, tudo bem? 

Estou tendo o seguinte erro abaixo na instalação do módulo python erpbrasil.base. 
Quando digito o comando pip3 install erpbrasil.base dá o seguinte erro:

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-wk4z2asd/erpbrasil.base/

Alguém sabe me dizer como faço para corrigir isso? 

Obrigado

**Comment by netosjb** [comment]
@thiagoblisboa consegue postar o trace error completo ?

**Comment by thiagoblisboa** [comment]
Muito obrigado @netosjb . Estava faltando o módulo setuptools e wheel… Instalei os dois módulos e consegui fazer a instalação do modulo erpbrasil.base porém, quando reinicio o servidor para fazer efeito a instalação, todos os módulos somem, como se não estivessem instalado.

**Comment by netosjb** [comment]
@thiagoblisboa com certeza você está algum problema de configuração no seu servidor, já que o problema não é na biblioteca sugiro o fechamento da issue.
