### ISSUE TITLE
Atualização na validação da IE de Goiás.

### ISSUE THREAD

**Issue by antoniospneto** [erpbrasil/erpbrasil.base#48]
É preciso alterar a logica de validação de Goiás:

Ano passado houve mudanças na incrição:

https://bbcconsultoria.com.br/secao.asp?id_secao=11485#:~:text=Entenda%20%2D%20A%20Inscri%C3%A7%C3%A3o%20Estadual%20em,no%20caso%20de%20Pessoa%20F%C3%ADsica.

Agora é possivel ter inscrições estaduais iniciadas com 20. exemplo:  20.021.462-4

https://github.com/erpbrasil/erpbrasil.base/blob/8c3e4dd0a7a74287a357c978328a5187e36d2ab0/src/erpbrasil/base/fiscal/ie.py#L258-L261

**Comment by mileo** [comment]
Já implementado?
